[[dependency]]
org = "ballerinax"
name = "slack"
version = "0.9.9-SNAPSHOT"

[[dependency]]
org = "ballerina"
name = "websub"
version = "1.2.0-beta.2"

[[dependency]]
org = "ballerinax"
name = "github"
version = "0.99.15-SNAPSHOT"

[[dependency]]
org = "ballerina"
name = "http"
version = "1.1.0-beta.2"

[[dependency]]
org = "ballerina"
name = "log"
version = "1.1.0-beta.2"

[[dependency]]
org = "ballerina"
name = "os"
version = "0.8.0-beta.2"

[[dependency]]
org = "ballerina"
name = "mime"
version = "1.1.0-beta.2"

[[dependency]]
org = "ballerina"
name = "regex"
version = "0.7.0-beta.2"

[[dependency]]
org = "ballerina"
name = "url"
version = "1.1.0-beta.2"

[[dependency]]
org = "ballerina"
name = "time"
version = "2.0.0-beta.2"
