[[dependency]]
org = "ballerina"
name = "log"
version = "1.1.0-beta.2"

[[dependency]]
org = "ballerina"
name = "http"
version = "1.1.0-beta.2"

[[dependency]]
org = "ballerina"
name = "lang.array"
version = "2.0.0-beta.2"

[[dependency]]
org = "ballerinax"
name = "googleapis.drive"
version = "0.1.4-SNAPSHOT"

[[dependency]]
org = "ballerinax"
name = "googleapis.gmail"
version = "0.99.8-SNAPSHOT"
