[[dependency]]
org = "ballerinax"
name = "googleapis.gmail"
version = "0.99.8-SNAPSHOT"

[[dependency]]
org = "ballerinax"
name = "twilio"
version = "0.99.9-SNAPSHOT"

[[dependency]]
org = "ballerina"
name = "log"
version = "1.1.0-beta.2"
