[[dependency]]
org = "ballerina"
name = "http"
version = "1.1.0-beta.2"

[[dependency]]
org = "ballerina"
name = "log"
version = "1.1.0-beta.2"

[[dependency]]
org = "ballerinax"
name = "twilio"
version = "0.99.9-SNAPSHOT"

[[dependency]]
org = "ballerinax"
name = "googleapis.drive"
version = "0.1.4-SNAPSHOT"
