[[dependency]]
org = "ballerinax"
name = "azure_storage_service"
version = "0.1.2-SNAPSHOT"

[[dependency]]
org = "ballerinax"
name = "sfdc"
version = "2.1.9-SNAPSHOT"

[[dependency]]
org = "ballerina"
name = "log"
version = "1.1.0-beta.2"

[[dependency]]
org = "ballerinax"
name = "http"
version = "1.1.0-beta.2"

[[dependency]]
org = "ballerinax"
name = "time"
version = "2.0.0-beta.2"
