[[dependency]]
org = "ballerinax"
name = "twilio"
version = "0.99.9-SNAPSHOT"

[[dependency]]
org = "ballerinax"
name = "googleapis.sheets"
version = "0.99.9-SNAPSHOT"

[[dependency]]
org = "ballerina"
name = "log"
version = "1.1.0-beta.2"

[[dependency]]
org = "ballerina"
name = "log"
version = "1.1.0-beta.2"

[[dependency]]
org = "ballerina"
name = "lang.int"
version = "1.1.0-beta.2"

[[dependency]]
org = "ballerina"
name = "url"
version = "1.1.0-beta.2"

[[dependency]]
org = "ballerina"
name = "regex"
version = "0.7.0-beta.2"
