[[dependency]]
org = "ballerinax"
name = "slack"
version = "0.9.9-SNAPSHOT"

[[dependency]]
org = "ballerinax"
name = "sfdc"
version = "2.1.9-SNAPSHOT"

[[dependency]]
org = "ballerina"
name = "io"
version = "0.6.0-beta.2"

[[dependency]]
org = "ballerina"
name = "log"
version = "1.1.0-beta.2"

[[dependency]]
org = "ballerina"
name = "http"
version = "1.1.0-beta.2"

[[dependency]]
org = "ballerina"
name = "url"
version = "1.1.0-beta.2"

[[dependency]]
org = "ballerina"
name = "regex"
version = "0.7.0-beta.2"

[[dependency]]
org = "ballerina"
name = "time"
version = "2.0.0-beta.2"

[[dependency]]
org = "ballerina"
name = "mime"
version = "1.1.0-beta.2"
