[[dependency]]
org = "ballerinax"
name = "googleapis.calendar"
version = "0.1.6-SNAPSHOT"

[[dependency]]
org = "ballerinax"
name = "twilio"
version = "0.99.9-SNAPSHOT"

[[dependency]]
org = "ballerina"
name = "http"
version = "1.1.0-beta.2"

[[dependency]]
org = "ballerina"
name = "log"
version = "1.1.0-beta.2"

[[dependency]]
org = "ballerina"
name = "time"
version = "2.0.0-beta.2"

[[dependency]]
org = "ballerina"
name = "url"
version = "1.1.0-beta.2"

[[dependency]]
org = "ballerina"
name = "os"
version = "0.8.0-beta.2"

[[dependency]]
org = "ballerina"
name = "uuid"
version = "0.10.0-beta.2"

[[dependency]]
org = "ballerina"
name = "task"
version = "2.0.0-beta.2"

[[dependency]]
org = "ballerina"
name = "jwt"
version = "1.1.0-beta.2"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "1.1.0-beta.2"

[[dependency]]
org = "ballerina"
name = "auth"
version = "1.1.0-beta.2"

[[dependency]]
org = "ballerina"
name = "io"
version = "0.6.0-beta.2"

[[dependency]]
org = "ballerina"
name = "mime"
version = "1.1.0-beta.2"
