[[dependency]]
org = "ballerina"
name = "http"
version = "1.1.0-beta.2"

[[dependency]]
org = "ballerina"
name = "log"
version = "1.1.0-beta.2"

[[dependency]]
org = "ballerina"
name = "websub"
version = "1.2.0-beta.2"

[[dependency]]
org = "ballerinax"
name = "googleapis.sheets"
version = "0.99.9-SNAPSHOT"

[[dependency]]
org = "ballerinax"
name = "github"
version = "0.99.15-SNAPSHOT"
