# This is a basic workflow that is manually triggered

name: Pull Request Check

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request:
    branches:
      - main
jobs:
  check-pull-request:
    name: Check pull request
    if: github.repository == 'wso2/choreo-samples'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.10
          java-package: jdk
          architecture: x64 
      - name: Read Properties
        id: read_property
        uses:  ashley-taylor/read-json-property-action@v1.0
        with:
           path: runtimeproperties.json
           property: bal_dist_version
      - name: Download ballerina distribution
        uses: wei/wget@v1
        with:
          args: http://dist-dev.ballerina.io/downloads/${{ steps.read_property.outputs.value }}/ballerina-${{ steps.read_property.outputs.value }}.zip
      - run: mkdir extractedDistribution
      - name: Unzip ballerina distribution
        uses: montudor/action-zip@v0.1.0
        with:
          args: unzip -qq ballerina-${{ steps.read_property.outputs.value }}.zip -d extractedDistribution  
      - run: sudo cp -R /home/runner/work/choreo-samples/choreo-samples/bala/ballerinax /home/runner/work/choreo-samples/choreo-samples/extractedDistribution/ballerina-${{ steps.read_property.outputs.value }}/distributions/ballerina-slalpha5/repo/bala/
      - run: sudo cp -R /home/runner/work/choreo-samples/choreo-samples/bala/ballerinax /home/runner/work/choreo-samples/choreo-samples/extractedDistribution/ballerina-${{ steps.read_property.outputs.value }}/distributions/ballerina-slalpha5/repo/cache/
      - run: sudo chmod -R 777 /home/runner/work/choreo-samples/choreo-samples/extractedDistribution/ballerina-${{ steps.read_property.outputs.value }}/distributions/ballerina-slalpha5/repo/bala
      - run: sudo chmod -R 777 /home/runner/work/choreo-samples/choreo-samples/extractedDistribution/ballerina-${{ steps.read_property.outputs.value }}/distributions/ballerina-slalpha5/repo/cache
      - name: set environment variables
        uses: allenevans/set-env@v2.0.0
        with:
          BALLERINA_SDK_PATH: '/home/runner/work/choreo-samples/choreo-samples/extractedDistribution/ballerina-${{ steps.read_property.outputs.value }}/distributions/ballerina-slalpha5/'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run gen-st

      